#!/usr/bin/env bash
# Perform a reproducible build and run tests using Bazel

# Set up Git repository
mkdir -p bazel
git clone --depth 1 -b evm-rpc-canister https://github.com/dfinity/ic.git bazel/ic
cd bazel/ic || exit 1
test -d .git || exit 1
git pull
ln -fs ../../../.. rs/ethereum/evm_rpc

# Build and test in reproducible environment
bazel build //rs/ethereum/evm_rpc:evm_rpc --config=local || exit 1
# bazel test //rs/ethereum/evm_rpc:unit_tests //rs/ethereum/evm_rpc:integration_tests --config=local || exit 1

# Display the SHA-256 hash of the canister Wasm
sha256sum bazel/ic/bazel-bin/rs/ethereum/evm_rpc/evm_rpc.wasm
