#!/usr/bin/env bash

set -euo pipefail
set -x

# Make sure we always run from the root
SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPTS_DIR/.."

#########
# USAGE #
#########

function title() {
    echo "Builds EVM RPC canister"
}

function usage() {
    cat << EOF

Usage:
  $0 [--only-dependencies]

Options:
  --only-dependencies          only build rust dependencies (no js build, no wasm optimization)
EOF
}

function help() {
    cat << EOF

Builds the EVM RPC canister.

NOTE: This requires a working rust toolchain as well as ic-wasm.
EOF

}

ONLY_DEPS=
RUN_CARGO_TEST=
CANISTERS=()

while [[ $# -gt 0  ]]
do
    case "$1" in
        -h|--help)
            title
            usage
            help
            exit 0
            ;;
        --only-dependencies)
            ONLY_DEPS=1
            shift
            ;;
        --test)
            RUN_CARGO_TEST=1
            shift
            ;;
        --evm-rpc)
            CANISTERS+=("evm_rpc")
            shift
            ;;
        *)
            echo "ERROR: unknown argument $1"
            usage
            echo
            echo "Use 'build --help' for more information"
            exit 1
            ;;
    esac
done

# Checking for dependencies
if [[ ! "$(command -v ic-wasm)" || "$(ic-wasm --version)" != "ic-wasm 0.3.5" ]]
then
    echo "could not find ic-wasm 0.3.5"
    echo "ic-wasm version 0.3.5 is needed, please run the following command:"
    echo "  cargo install ic-wasm --version 0.3.5"
    exit 1
fi

function build_canister() {
    local canister=$1
    shift
    local extra_build_args=("$@")

    echo "Building $canister"
    echo

    SRC_DIR="/src"
    TARGET="wasm32-unknown-unknown"
    # standardize source references
    CARGO_HOME="${CARGO_HOME:-"$HOME/.cargo"}"
    RUSTFLAGS="--remap-path-prefix $CARGO_HOME=/cargo"

    cargo_build_args=(
        --target "$TARGET"
        --release
        -j1
        )
    # XXX: for bash > 4.4, empty arrays are considered unset, so do some substitution
    cargo_build_args+=(${extra_build_args[@]+"${extra_build_args[@]}"})

    echo Running cargo build "${cargo_build_args[@]}"
    echo RUSTFLAGS: "$RUSTFLAGS"

    RUSTFLAGS="$RUSTFLAGS" cargo build "${cargo_build_args[@]}"

    if [ "$RUN_CARGO_TEST" == "1" ]
    then
        cargo test
    fi

    if [ "$ONLY_DEPS" != "1" ]
    then
        ic-wasm \
            "./target/$TARGET/release/$canister.wasm" \
            -o "./$canister.wasm" \
            shrink
        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:service -f "candid/$canister.did" -v public

        # Indicate the EVM RPC canister init argument type
        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata candid:args -d "(InstallArgs)" -v public

        # Write metadata for dfx
        asset_name="evm_rpc.wasm.gz"
        wasm_url="https://github.com/internet-computer-protocol/evm-rpc-canister/releases/latest/download/evm_rpc.wasm.gz"
        init_guide="https://internetcomputer.org/docs/current/developer-docs/multi-chain/ethereum/evm-rpc/evm-rpc-canister"
        metadata_json=$(echo '{}' | jq -cMr \
            --arg wasm_url "$wasm_url" \
            --arg init_guide "$init_guide" \
            '. | .pullable = { wasm_url: $wasm_url, dependencies: [], init_guide: $init_guide} ')
        ic-wasm "$canister.wasm" -o "$canister.wasm" metadata dfx -d "$metadata_json" -v public

        gzip --no-name --force "$canister.wasm"
    fi
}

for canister in "${CANISTERS[@]}"
do
    build_canister "$canister"
done
